//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Lenguaje {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.Lenguaje.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Btn_Agregar {
            get {
                return ResourceManager.GetString("Btn_Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al pedido.
        /// </summary>
        internal static string Btn_AgregarAlPedido {
            get {
                return ResourceManager.GetString("Btn_AgregarAlPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar a la compra.
        /// </summary>
        internal static string Btn_AgregarCompra {
            get {
                return ResourceManager.GetString("Btn_AgregarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de personas.
        /// </summary>
        internal static string Btn_AltaPersonas {
            get {
                return ResourceManager.GetString("Btn_AltaPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociar cliente.
        /// </summary>
        internal static string Btn_AsociarCliente {
            get {
                return ResourceManager.GetString("Btn_AsociarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociar usuario.
        /// </summary>
        internal static string Btn_AsociarUsuario {
            get {
                return ResourceManager.GetString("Btn_AsociarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitácora.
        /// </summary>
        internal static string Btn_Bitacora {
            get {
                return ResourceManager.GetString("Btn_Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Btn_Buscar {
            get {
                return ResourceManager.GetString("Btn_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar cliente.
        /// </summary>
        internal static string Btn_BuscarCliente {
            get {
                return ResourceManager.GetString("Btn_BuscarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        internal static string Btn_Catalogo {
            get {
                return ResourceManager.GetString("Btn_Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string Btn_CerraSesion {
            get {
                return ResourceManager.GetString("Btn_CerraSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de Sistema.
        /// </summary>
        internal static string Btn_ConfSistema {
            get {
                return ResourceManager.GetString("Btn_ConfSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar OC.
        /// </summary>
        internal static string Btn_ConfTotal {
            get {
                return ResourceManager.GetString("Btn_ConfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar venta.
        /// </summary>
        internal static string Btn_ConsultaVentas {
            get {
                return ResourceManager.GetString("Btn_ConsultaVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cliente.
        /// </summary>
        internal static string Btn_CrearCliente {
            get {
                return ResourceManager.GetString("Btn_CrearCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descartar OC.
        /// </summary>
        internal static string Btn_Descartar {
            get {
                return ResourceManager.GetString("Btn_Descartar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Btn_Eliminar {
            get {
                return ResourceManager.GetString("Btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Btn_Eliminar1 {
            get {
                return ResourceManager.GetString("Btn_Eliminar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar de la compra.
        /// </summary>
        internal static string Btn_EliminardeCompra {
            get {
                return ResourceManager.GetString("Btn_EliminardeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar de pedido.
        /// </summary>
        internal static string Btn_EliminardePedido {
            get {
                return ResourceManager.GetString("Btn_EliminardePedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar compra.
        /// </summary>
        internal static string Btn_FinalizarCompra {
            get {
                return ResourceManager.GetString("Btn_FinalizarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Pedido.
        /// </summary>
        internal static string Btn_FinalizarPedido {
            get {
                return ResourceManager.GetString("Btn_FinalizarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Función.
        /// </summary>
        internal static string Btn_Funcion {
            get {
                return ResourceManager.GetString("Btn_Funcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        internal static string Btn_GenerarInforme {
            get {
                return ResourceManager.GetString("Btn_GenerarInforme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de altas.
        /// </summary>
        internal static string Btn_GestionAltas {
            get {
                return ResourceManager.GetString("Btn_GestionAltas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de stock.
        /// </summary>
        internal static string Btn_GestionStock {
            get {
                return ResourceManager.GetString("Btn_GestionStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de ventas.
        /// </summary>
        internal static string Btn_GestionVentas {
            get {
                return ResourceManager.GetString("Btn_GestionVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Btn_Guardar {
            get {
                return ResourceManager.GetString("Btn_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        internal static string Btn_GuardarCambios {
            get {
                return ResourceManager.GetString("Btn_GuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Btn_GuardarPass {
            get {
                return ResourceManager.GetString("Btn_GuardarPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial.
        /// </summary>
        internal static string Btn_Historial {
            get {
                return ResourceManager.GetString("Btn_Historial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        internal static string Btn_Informes {
            get {
                return ResourceManager.GetString("Btn_Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string Btn_Ingresar {
            get {
                return ResourceManager.GetString("Btn_Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Btn_Modificar {
            get {
                return ResourceManager.GetString("Btn_Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        internal static string Btn_ModuloAdministracion {
            get {
                return ResourceManager.GetString("Btn_ModuloAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Órden de compra.
        /// </summary>
        internal static string Btn_OrdendeCompra {
            get {
                return ResourceManager.GetString("Btn_OrdendeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido de compra.
        /// </summary>
        internal static string Btn_PedidodeCompra {
            get {
                return ResourceManager.GetString("Btn_PedidodeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        internal static string Btn_Proveedores {
            get {
                return ResourceManager.GetString("Btn_Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refrescar.
        /// </summary>
        internal static string Btn_Refrescar {
            get {
                return ResourceManager.GetString("Btn_Refrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Btn_RegistrarCliente {
            get {
                return ResourceManager.GetString("Btn_RegistrarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Btn_RegistrarPersona {
            get {
                return ResourceManager.GetString("Btn_RegistrarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Btn_RegistrarUsuario {
            get {
                return ResourceManager.GetString("Btn_RegistrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        internal static string Btn_Seguridad {
            get {
                return ResourceManager.GetString("Btn_Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar persona.
        /// </summary>
        internal static string Btn_SeleccionarPersona {
            get {
                return ResourceManager.GetString("Btn_SeleccionarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string Btn_SeleccionarProveedor {
            get {
                return ResourceManager.GetString("Btn_SeleccionarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos con bajo stock.
        /// </summary>
        internal static string Btn_StockCritico {
            get {
                return ResourceManager.GetString("Btn_StockCritico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de usuarios.
        /// </summary>
        internal static string Btn_Usuarios {
            get {
                return ResourceManager.GetString("Btn_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        internal static string Btn_Ventas {
            get {
                return ResourceManager.GetString("Btn_Ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        internal static string Btn_Ver {
            get {
                return ResourceManager.GetString("Btn_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos vencidos.
        /// </summary>
        internal static string Btn_VerProdVencidos {
            get {
                return ResourceManager.GetString("Btn_VerProdVencidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver todo.
        /// </summary>
        internal static string Btn_VerTodo {
            get {
                return ResourceManager.GetString("Btn_VerTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos próximos a vencer.
        /// </summary>
        internal static string Btn_VtoProductos {
            get {
                return ResourceManager.GetString("Btn_VtoProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea realizar una búsqueda?.
        /// </summary>
        internal static string Chb_Busqueda {
            get {
                return ResourceManager.GetString("Chb_Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener un caracter especial.
        /// </summary>
        internal static string Chb_CaracEspec {
            get {
                return ResourceManager.GetString("Chb_CaracEspec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede contener datos personales.
        /// </summary>
        internal static string Chb_DatosPersonales {
            get {
                return ResourceManager.GetString("Chb_DatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IIBB.
        /// </summary>
        internal static string Chb_IIBB {
            get {
                return ResourceManager.GetString("Chb_IIBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener una minúscula y una mayúscula.
        /// </summary>
        internal static string Chb_MayMin {
            get {
                return ResourceManager.GetString("Chb_MayMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener mínimo 8 caracteres.
        /// </summary>
        internal static string Chb_MinCaracteres {
            get {
                return ResourceManager.GetString("Chb_MinCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe combinar numeros y letras.
        /// </summary>
        internal static string Chb_NumYLetras {
            get {
                return ResourceManager.GetString("Chb_NumYLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede repetir contraseñas.
        /// </summary>
        internal static string Chb_RepetirPass {
            get {
                return ResourceManager.GetString("Chb_RepetirPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta usuarios.
        /// </summary>
        internal static string CV_AltaUsuario {
            get {
                return ResourceManager.GetString("CV_AltaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de productos.
        /// </summary>
        internal static string CV_CatalogoProductos {
            get {
                return ResourceManager.GetString("CV_CatalogoProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de Sistema.
        /// </summary>
        internal static string CV_ConfiguracionSistema {
            get {
                return ResourceManager.GetString("CV_ConfiguracionSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de ventas.
        /// </summary>
        internal static string CV_ConsultaVentas {
            get {
                return ResourceManager.GetString("CV_ConsultaVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Órden de compra.
        /// </summary>
        internal static string CV_GestionOrdendeCompra {
            get {
                return ResourceManager.GetString("CV_GestionOrdendeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de proveedores.
        /// </summary>
        internal static string CV_GestiónProveedores {
            get {
                return ResourceManager.GetString("CV_GestiónProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Stock.
        /// </summary>
        internal static string CV_GestionStock {
            get {
                return ResourceManager.GetString("CV_GestionStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de Personas.
        /// </summary>
        internal static string CV_GestionUsuariosPersonas {
            get {
                return ResourceManager.GetString("CV_GestionUsuariosPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        internal static string CV_Informes {
            get {
                return ResourceManager.GetString("CV_Informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string CV_Login {
            get {
                return ResourceManager.GetString("CV_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        internal static string CV_Menu {
            get {
                return ResourceManager.GetString("CV_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulo de seguridad.
        /// </summary>
        internal static string CV_ModulodeSeguridad {
            get {
                return ResourceManager.GetString("CV_ModulodeSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener Clientes.
        /// </summary>
        internal static string CV_ObtenerClientes {
            get {
                return ResourceManager.GetString("CV_ObtenerClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener proveedores.
        /// </summary>
        internal static string CV_ObtenerProveedores {
            get {
                return ResourceManager.GetString("CV_ObtenerProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        internal static string CV_OlvidoPass {
            get {
                return ResourceManager.GetString("CV_OlvidoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido de Compra.
        /// </summary>
        internal static string CV_PedidodeCompra {
            get {
                return ResourceManager.GetString("CV_PedidodeCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar persona.
        /// </summary>
        internal static string CV_SeleccionarPersona {
            get {
                return ResourceManager.GetString("CV_SeleccionarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        internal static string CV_Ventas {
            get {
                return ResourceManager.GetString("CV_Ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string Gpb_Permisos {
            get {
                return ResourceManager.GetString("Gpb_Permisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preguntas de seguridad.
        /// </summary>
        internal static string Gpb_PregSeg {
            get {
                return ResourceManager.GetString("Gpb_PregSeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de nalisis.
        /// </summary>
        internal static string Lbl_Analisis {
            get {
                return ResourceManager.GetString("Lbl_Analisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Lbl_Apellido {
            get {
                return ResourceManager.GetString("Lbl_Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Lbl_Buscar {
            get {
                return ResourceManager.GetString("Lbl_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar cliente.
        /// </summary>
        internal static string Lbl_BuscarCliente {
            get {
                return ResourceManager.GetString("Lbl_BuscarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Persona.
        /// </summary>
        internal static string Lbl_BuscarPersona {
            get {
                return ResourceManager.GetString("Lbl_BuscarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar en catálogo.
        /// </summary>
        internal static string Lbl_BusqCatalogo {
            get {
                return ResourceManager.GetString("Lbl_BusqCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda rápida.
        /// </summary>
        internal static string Lbl_BusquedaRapida {
            get {
                return ResourceManager.GetString("Lbl_BusquedaRapida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener un caracter especial.
        /// </summary>
        internal static string Lbl_CacaterEspecial {
            get {
                return ResourceManager.GetString("Lbl_CacaterEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad desde.
        /// </summary>
        internal static string Lbl_CantDesde {
            get {
                return ResourceManager.GetString("Lbl_CantDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hasta.
        /// </summary>
        internal static string Lbl_CantHasta {
            get {
                return ResourceManager.GetString("Lbl_CantHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Lbl_Cantidad {
            get {
                return ResourceManager.GetString("Lbl_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de intentos fallidos.
        /// </summary>
        internal static string Lbl_CantIntentosFallidos {
            get {
                return ResourceManager.GetString("Lbl_CantIntentosFallidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad mínima de stock.
        /// </summary>
        internal static string Lbl_CantMinStock {
            get {
                return ResourceManager.GetString("Lbl_CantMinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito de compras.
        /// </summary>
        internal static string Lbl_Carrito {
            get {
                return ResourceManager.GetString("Lbl_Carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito del pedido de compra.
        /// </summary>
        internal static string Lbl_CarritoPC {
            get {
                return ResourceManager.GetString("Lbl_CarritoPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        internal static string Lbl_Catalogo {
            get {
                return ResourceManager.GetString("Lbl_Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        internal static string Lbl_Categoria {
            get {
                return ResourceManager.GetString("Lbl_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Lbl_Cliente {
            get {
                return ResourceManager.GetString("Lbl_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string Lbl_CoincidePass {
            get {
                return ResourceManager.GetString("Lbl_CoincidePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string Lbl_ComentarioCliente {
            get {
                return ResourceManager.GetString("Lbl_ComentarioCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string Lbl_Comentarios {
            get {
                return ResourceManager.GetString("Lbl_Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compra mínima desde.
        /// </summary>
        internal static string Lbl_CompraMinDesde {
            get {
                return ResourceManager.GetString("Lbl_CompraMinDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hasta.
        /// </summary>
        internal static string Lbl_CompraMinHasta {
            get {
                return ResourceManager.GetString("Lbl_CompraMinHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compra minima.
        /// </summary>
        internal static string Lbl_CompraMinima {
            get {
                return ResourceManager.GetString("Lbl_CompraMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cond. IVA.
        /// </summary>
        internal static string Lbl_CondIVA {
            get {
                return ResourceManager.GetString("Lbl_CondIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string Lbl_ConfContrasena {
            get {
                return ResourceManager.GetString("Lbl_ConfContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string Lbl_ConfPass {
            get {
                return ResourceManager.GetString("Lbl_ConfPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Lbl_Contrasena {
            get {
                return ResourceManager.GetString("Lbl_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Lbl_Correo {
            get {
                return ResourceManager.GetString("Lbl_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIT.
        /// </summary>
        internal static string Lbl_Cuit {
            get {
                return ResourceManager.GetString("Lbl_Cuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede contener datos personales.
        /// </summary>
        internal static string Lbl_DatosPersonales {
            get {
                return ResourceManager.GetString("Lbl_DatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción descuento.
        /// </summary>
        internal static string Lbl_DescCateg {
            get {
                return ResourceManager.GetString("Lbl_DescCateg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string Lbl_Descripcion {
            get {
                return ResourceManager.GetString("Lbl_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descuento aplicado.
        /// </summary>
        internal static string Lbl_DescuentoAplicado {
            get {
                return ResourceManager.GetString("Lbl_DescuentoAplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string Lbl_Desde {
            get {
                return ResourceManager.GetString("Lbl_Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días para el vencimiento de productos.
        /// </summary>
        internal static string Lbl_DiasVtoProd {
            get {
                return ResourceManager.GetString("Lbl_DiasVtoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        internal static string Lbl_Direccion {
            get {
                return ResourceManager.GetString("Lbl_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        internal static string Lbl_Documento {
            get {
                return ResourceManager.GetString("Lbl_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        internal static string Lbl_Domicilio {
            get {
                return ResourceManager.GetString("Lbl_Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string Lbl_Estado {
            get {
                return ResourceManager.GetString("Lbl_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        internal static string Lbl_Familia {
            get {
                return ResourceManager.GetString("Lbl_Familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de alta.
        /// </summary>
        internal static string Lbl_FeAltaCliente {
            get {
                return ResourceManager.GetString("Lbl_FeAltaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de alta.
        /// </summary>
        internal static string Lbl_FechaAlta {
            get {
                return ResourceManager.GetString("Lbl_FechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desde.
        /// </summary>
        internal static string Lbl_FechaHasta {
            get {
                return ResourceManager.GetString("Lbl_FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inicio.
        /// </summary>
        internal static string Lbl_FechaInicio {
            get {
                return ResourceManager.GetString("Lbl_FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha desde.
        /// </summary>
        internal static string Lbl_FeDesde {
            get {
                return ResourceManager.GetString("Lbl_FeDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hasta.
        /// </summary>
        internal static string Lbl_FeHasta {
            get {
                return ResourceManager.GetString("Lbl_FeHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        internal static string Lbl_FeNacimiento {
            get {
                return ResourceManager.GetString("Lbl_FeNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string Lbl_Hasta {
            get {
                return ResourceManager.GetString("Lbl_Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        internal static string Lbl_Lenguaje {
            get {
                return ResourceManager.GetString("Lbl_Lenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        internal static string Lbl_Localidad {
            get {
                return ResourceManager.GetString("Lbl_Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote N°.
        /// </summary>
        internal static string Lbl_LoteBusq {
            get {
                return ResourceManager.GetString("Lbl_LoteBusq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string Lbl_Marca {
            get {
                return ResourceManager.GetString("Lbl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula N°.
        /// </summary>
        internal static string Lbl_Matrícula {
            get {
                return ResourceManager.GetString("Lbl_Matrícula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe combinar mayúsculas y minúsculas.
        /// </summary>
        internal static string Lbl_MayusMinus {
            get {
                return ResourceManager.GetString("Lbl_MayusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener mínimo 8 caracteres.
        /// </summary>
        internal static string Lbl_MinCaracteres {
            get {
                return ResourceManager.GetString("Lbl_MinCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monodroga.
        /// </summary>
        internal static string Lbl_Monodroga {
            get {
                return ResourceManager.GetString("Lbl_Monodroga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacionalidad.
        /// </summary>
        internal static string Lbl_Nacionalidad {
            get {
                return ResourceManager.GetString("Lbl_Nacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Lbl_Nombre {
            get {
                return ResourceManager.GetString("Lbl_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre comercial.
        /// </summary>
        internal static string Lbl_NombreComercial {
            get {
                return ResourceManager.GetString("Lbl_NombreComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lote N°.
        /// </summary>
        internal static string Lbl_NroLote {
            get {
                return ResourceManager.GetString("Lbl_NroLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener numeros y letras.
        /// </summary>
        internal static string Lbl_NumerosYLetras {
            get {
                return ResourceManager.GetString("Lbl_NumerosYLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partido.
        /// </summary>
        internal static string Lbl_Partido {
            get {
                return ResourceManager.GetString("Lbl_Partido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Lbl_Pass {
            get {
                return ResourceManager.GetString("Lbl_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio desde.
        /// </summary>
        internal static string Lbl_PrecDesde {
            get {
                return ResourceManager.GetString("Lbl_PrecDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hasta.
        /// </summary>
        internal static string Lbl_PrecHasta {
            get {
                return ResourceManager.GetString("Lbl_PrecHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string Lbl_Precio {
            get {
                return ResourceManager.GetString("Lbl_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio por lote.
        /// </summary>
        internal static string Lbl_PrecioPorLote {
            get {
                return ResourceManager.GetString("Lbl_PrecioPorLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado con éxito.
        /// </summary>
        internal static string Lbl_PregGuardada {
            get {
                return ResourceManager.GetString("Lbl_PregGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta 1.
        /// </summary>
        internal static string Lbl_Pregunta1 {
            get {
                return ResourceManager.GetString("Lbl_Pregunta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta 2.
        /// </summary>
        internal static string Lbl_Pregunta2 {
            get {
                return ResourceManager.GetString("Lbl_Pregunta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta 3.
        /// </summary>
        internal static string Lbl_Pregunta3 {
            get {
                return ResourceManager.GetString("Lbl_Pregunta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        internal static string Lbl_Proveedor {
            get {
                return ResourceManager.GetString("Lbl_Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón social.
        /// </summary>
        internal static string Lbl_RazonSocial {
            get {
                return ResourceManager.GetString("Lbl_RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta 1.
        /// </summary>
        internal static string Lbl_Respuesta1 {
            get {
                return ResourceManager.GetString("Lbl_Respuesta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta 2.
        /// </summary>
        internal static string Lbl_Respuesta2 {
            get {
                return ResourceManager.GetString("Lbl_Respuesta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta 3.
        /// </summary>
        internal static string Lbl_Respuesta3 {
            get {
                return ResourceManager.GetString("Lbl_Respuesta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        internal static string Lbl_Sexo {
            get {
                return ResourceManager.GetString("Lbl_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Lbl_Telefono {
            get {
                return ResourceManager.GetString("Lbl_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Lbl_Tipo {
            get {
                return ResourceManager.GetString("Lbl_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades por lote.
        /// </summary>
        internal static string Lbl_UnidadesporLote {
            get {
                return ResourceManager.GetString("Lbl_UnidadesporLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Lbl_UserName {
            get {
                return ResourceManager.GetString("Lbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Lbl_Usuario {
            get {
                return ResourceManager.GetString("Lbl_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Lbl_Usuario1 {
            get {
                return ResourceManager.GetString("Lbl_Usuario1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Lbl_Usuario2 {
            get {
                return ResourceManager.GetString("Lbl_Usuario2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vence cada.
        /// </summary>
        internal static string Lbl_VenceCada {
            get {
                return ResourceManager.GetString("Lbl_VenceCada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencimiento.
        /// </summary>
        internal static string Lbl_Vto {
            get {
                return ResourceManager.GetString("Lbl_Vto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencimiento desde.
        /// </summary>
        internal static string Lbl_VtoDesde {
            get {
                return ResourceManager.GetString("Lbl_VtoDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string Lbl_VtoHasta {
            get {
                return ResourceManager.GetString("Lbl_VtoHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Llb_Contrasena {
            get {
                return ResourceManager.GetString("Llb_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        internal static string LnkLbl_OlvideContrasena {
            get {
                return ResourceManager.GetString("LnkLbl_OlvideContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        internal static string Rbt_Grupo {
            get {
                return ResourceManager.GetString("Rbt_Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string Rbt_Usuario {
            get {
                return ResourceManager.GetString("Rbt_Usuario", resourceCulture);
            }
        }
    }
}
